import { Link } from 'react-router-dom'
import {
  ListTodo, Workflow, GitBranch, Mail, Calendar, GitCommitHorizontal,
  GitPullRequest, ShieldCheck, ScrollText, BarChart3, ArrowRight, LayoutDashboard,
} from 'lucide-react'
import { useAuthStore } from '@/store/authStore'

const FEATURES = [
  { icon: ListTodo, title: 'Tasks', description: 'Track and manage work generated by your automations.' },
  { icon: Workflow, title: 'Workflow Automations', description: 'Configure a trigger (GitHub push, issue, or pull request) and one or more actions that run automatically when it fires.' },
  { icon: GitBranch, title: 'GitHub', description: 'Connect repositories so WorkForge can react to pushes, issues, and pull requests.' },
  { icon: GitCommitHorizontal, title: 'Commit Scheduler', description: 'Schedule and automate commits on a recurring basis.' },
  { icon: GitPullRequest, title: 'Pull Requests', description: 'Review, approve, and manage PRs from one place.' },
  { icon: Mail, title: 'Gmail', description: 'Detects job-application replies (interview, offer, rejection) in your inbox to update Job Hunter, and sends emails for workflows you configure.' },
  { icon: Calendar, title: 'Google Calendar', description: 'Creates interview events detected from Gmail, runs workflow-triggered event creation, and can optionally auto-block your lunch hour.' },
  { icon: ShieldCheck, title: 'Human Approval', description: 'Keep a human in the loop before automation takes action.' },
  { icon: ScrollText, title: 'Audit Logs', description: 'A full record of every automated and manual action.' },
  { icon: BarChart3, title: 'Analytics', description: 'Operational visibility into activity across your organization.' },
]

export default function Home() {
  const user = useAuthStore((s) => s.user)
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated)

  return (
    <div className="min-h-screen bg-[var(--color-void)] text-[var(--color-text-primary)]">
      <header className="border-b border-[var(--color-border)]">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <span className="font-[family-name:var(--font-display)] text-lg font-semibold">
            WorkForge
          </span>
          {isAuthenticated ? (
            <Link
              to="/dashboard"
              className="flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg bg-[var(--color-signal)] text-[var(--color-void)] hover:brightness-110 transition-all"
            >
              <LayoutDashboard size={14} />
              Dashboard
            </Link>
          ) : (
            <div className="flex items-center gap-3">
              <Link
                to="/login"
                className="text-sm text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] transition-colors"
              >
                Sign in
              </Link>
              <Link
                to="/signup"
                className="text-sm font-medium px-4 py-2 rounded-lg bg-[var(--color-signal)] text-[var(--color-void)] hover:brightness-110 transition-all"
              >
                Sign up
              </Link>
            </div>
          )}
        </div>
      </header>

      <main>
        <section className="max-w-4xl mx-auto px-6 pt-20 pb-16 text-center">
          <h1 className="font-[family-name:var(--font-display)] text-4xl md:text-5xl font-semibold leading-tight">
            Your automation runs while you're away
          </h1>
          <p className="mt-5 text-lg text-[var(--color-text-muted)] max-w-2xl mx-auto">
            WorkForge is a workflow automation platform. You connect services you authorize — GitHub, Gmail,
            Google Calendar, Discord — and configure triggers and actions so operational work (tasks, emails,
            calendar events, notifications) happens automatically based on events you define.
          </p>
          {isAuthenticated ? (
            <Link
              to="/dashboard"
              className="mt-8 inline-flex items-center gap-4 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]/60 backdrop-blur-xl px-5 py-4 hover:border-[var(--color-border-hover)] transition-colors text-left"
            >
              <div className="h-10 w-10 rounded-xl bg-[var(--color-signal-dim)] flex items-center justify-center shrink-0">
                <span className="text-sm font-semibold text-[var(--color-signal)]">
                  {(user?.full_name || user?.email || '?').charAt(0).toUpperCase()}
                </span>
              </div>
              <div className="min-w-0">
                <p className="text-sm font-medium text-[var(--color-text-primary)]">
                  {user?.organization_name || user?.full_name || 'Your workspace'}
                </p>
                <p className="text-xs text-[var(--color-text-faint)]">Open Overview</p>
              </div>
              <ArrowRight size={16} className="text-[var(--color-text-muted)] shrink-0 ml-2" />
            </Link>
          ) : (
            <div className="mt-8 flex items-center justify-center gap-4">
              <Link
                to="/signup"
                className="flex items-center gap-2 text-sm font-medium px-5 py-3 rounded-lg bg-[var(--color-signal)] text-[var(--color-void)] hover:brightness-110 transition-all"
              >
                Get started
                <ArrowRight size={15} />
              </Link>
              <Link
                to="/login"
                className="text-sm font-medium px-5 py-3 rounded-lg border border-[var(--color-border)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface-hover)] transition-colors"
              >
                Sign in
              </Link>
            </div>
          )}
        </section>

        <section className="max-w-6xl mx-auto px-6 pb-20">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]/60 backdrop-blur-xl p-5"
              >
                <div className="h-9 w-9 rounded-lg bg-[var(--color-signal-dim)] flex items-center justify-center mb-3">
                  <f.icon size={16} className="text-[var(--color-signal)]" />
                </div>
                <h3 className="text-sm font-medium text-[var(--color-text-primary)]">{f.title}</h3>
                <p className="mt-1 text-xs text-[var(--color-text-faint)] leading-relaxed">{f.description}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="max-w-4xl mx-auto px-6 pb-24">
          <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]/60 backdrop-blur-xl p-6 md:p-8">
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold text-[var(--color-text-primary)]">
              Why we request Google account access
            </h2>
            <p className="mt-3 text-sm text-[var(--color-text-muted)] leading-relaxed">
              WorkForge only requests access to your Google account to provide features you explicitly use —
              never for advertising, profiling, or any purpose unrelated to the app. For example:
            </p>
            <ul className="mt-4 flex flex-col gap-2.5 text-sm text-[var(--color-text-muted)]">
              <li className="flex gap-2.5">
                <span className="text-[var(--color-signal)]">→</span>
                <span>Connecting <strong className="text-[var(--color-text-primary)]">Gmail</strong> lets WorkForge detect recruiter emails (interview, offer, rejection) to update your Job Hunter tracker, and send emails as part of workflows you configure — for example, "GitHub push → send a notification email."</span>
              </li>
              <li className="flex gap-2.5">
                <span className="text-[var(--color-signal)]">→</span>
                <span>Connecting <strong className="text-[var(--color-text-primary)]">Google Calendar</strong> lets WorkForge create interview events detected from Gmail, create events as part of workflows you configure, and optionally auto-block a daily lunch window you set.</span>
              </li>
            </ul>
            <p className="mt-4 text-sm text-[var(--color-text-muted)]">
              WorkForge does not independently decide to send emails or create events — these actions only
              happen because you configured them. Full details are in our{' '}
              <Link to="/privacy" className="text-[var(--color-signal)] hover:brightness-110">Privacy Policy</Link>.
            </p>
          </div>
        </section>
      </main>

      <footer className="border-t border-[var(--color-border)]">
        <div className="max-w-6xl mx-auto px-6 py-6 flex flex-wrap items-center gap-x-6 gap-y-2 text-xs text-[var(--color-text-faint)]">
          <span>© {new Date().getFullYear()} WorkForge</span>
          <Link to="/privacy" className="hover:text-[var(--color-text-primary)] transition-colors">Privacy Policy</Link>
          <Link to="/security" className="hover:text-[var(--color-text-primary)] transition-colors">Security</Link>
          <Link to="/terms" className="hover:text-[var(--color-text-primary)] transition-colors">Terms of Service</Link>
        </div>
      </footer>
    </div>
  )
}
