import { Link } from 'react-router-dom'
import {
  ListTodo, Workflow, GitBranch, Mail, Calendar, GitCommitHorizontal,
  GitPullRequest, ShieldCheck, ScrollText, BarChart3, ArrowRight,
} from 'lucide-react'

const FEATURES = [
  { icon: ListTodo, title: 'Tasks', description: 'Track and manage work generated by your automations.' },
  { icon: Workflow, title: 'Workflow Automations', description: 'Build triggers and actions that run without you.' },
  { icon: GitBranch, title: 'GitHub', description: 'Connect repositories and let WorkForge act on your behalf.' },
  { icon: GitCommitHorizontal, title: 'Commit Scheduler', description: 'Schedule and automate commits on a recurring basis.' },
  { icon: GitPullRequest, title: 'Pull Requests', description: 'Review, approve, and manage PRs from one place.' },
  { icon: Mail, title: 'Gmail', description: 'Optional integration for inbox summaries and follow-ups.' },
  { icon: Calendar, title: 'Google Calendar', description: 'Optional integration for scheduling and event automation.' },
  { icon: ShieldCheck, title: 'Human Approval', description: 'Keep a human in the loop before automation takes action.' },
  { icon: ScrollText, title: 'Audit Logs', description: 'A full record of every automated and manual action.' },
  { icon: BarChart3, title: 'Analytics', description: 'Operational visibility into activity across your organization.' },
]

export default function Home() {
  return (
    <div className="min-h-screen bg-[var(--color-void)] text-[var(--color-text-primary)]">
      <header className="border-b border-[var(--color-border)]">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <span className="font-[family-name:var(--font-display)] text-lg font-semibold">
            WorkForge
          </span>
          <div className="flex items-center gap-3">
            <Link
              to="/login"
              className="text-sm text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] transition-colors"
            >
              Sign in
            </Link>
            <Link
              to="/signup"
              className="text-sm font-medium px-4 py-2 rounded-lg bg-[var(--color-signal)] text-[var(--color-void)] hover:brightness-110 transition-all"
            >
              Sign up
            </Link>
          </div>
        </div>
      </header>

      <main>
        <section className="max-w-4xl mx-auto px-6 pt-20 pb-16 text-center">
          <h1 className="font-[family-name:var(--font-display)] text-4xl md:text-5xl font-semibold leading-tight">
            Your automation runs while you're away
          </h1>
          <p className="mt-5 text-lg text-[var(--color-text-muted)] max-w-2xl mx-auto">
            WorkForge is an automation platform that manages tasks, workflows, and integrations across
            GitHub, Gmail, and Google Calendar — so operational work keeps moving even when you're not
            watching it.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4">
            <Link
              to="/signup"
              className="flex items-center gap-2 text-sm font-medium px-5 py-3 rounded-lg bg-[var(--color-signal)] text-[var(--color-void)] hover:brightness-110 transition-all"
            >
              Get started
              <ArrowRight size={15} />
            </Link>
            <Link
              to="/login"
              className="text-sm font-medium px-5 py-3 rounded-lg border border-[var(--color-border)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface-hover)] transition-colors"
            >
              Sign in
            </Link>
          </div>
        </section>

        <section className="max-w-6xl mx-auto px-6 pb-20">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]/60 backdrop-blur-xl p-5"
              >
                <div className="h-9 w-9 rounded-lg bg-[var(--color-signal-dim)] flex items-center justify-center mb-3">
                  <f.icon size={16} className="text-[var(--color-signal)]" />
                </div>
                <h3 className="text-sm font-medium text-[var(--color-text-primary)]">{f.title}</h3>
                <p className="mt-1 text-xs text-[var(--color-text-faint)] leading-relaxed">{f.description}</p>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="border-t border-[var(--color-border)]">
        <div className="max-w-6xl mx-auto px-6 py-6 flex flex-wrap items-center gap-x-6 gap-y-2 text-xs text-[var(--color-text-faint)]">
          <span>© {new Date().getFullYear()} WorkForge</span>
          <Link to="/privacy" className="hover:text-[var(--color-text-primary)] transition-colors">Privacy Policy</Link>
          <Link to="/terms" className="hover:text-[var(--color-text-primary)] transition-colors">Terms of Service</Link>
        </div>
      </footer>
    </div>
  )
}
